"""init

Revision ID: f2bbbda44ab9
Revises: 65e6e240edfe
Create Date: 2025-07-18 15:43:19.077629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f2bbbda44ab9'
down_revision: Union[str, Sequence[str], None] = '65e6e240edfe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('knowledge_decay_events', 'topic',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('knowledge_decay_events', 'last_interaction',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('knowledge_decay_events', 'predicted_forget_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('knowledge_decay_events', 'review_suggested',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('knowledge_decay_events', 'decay_model_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('knowledge_decay_events', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('learning_sessions', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('learning_sessions', 'topic',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('learning_sessions', 'content_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('learning_sessions', 'time_spent',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('learning_sessions', 'retention_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('learning_sessions', 'interaction_pattern',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('recall_cards', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('recall_cards', 'topic',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('recall_cards', 'keywords',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               nullable=False)
    op.alter_column('recall_cards', 'diagram_image_url',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('recall_cards', 'analogy',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('skill_scan_results', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('skill_scan_results', 'career_goal',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('skill_scan_results', 'recommended_pathway',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('skill_scan_results', 'recommended_pathway',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('skill_scan_results', 'career_goal',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('skill_scan_results', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('recall_cards', 'analogy',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('recall_cards', 'diagram_image_url',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('recall_cards', 'keywords',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               nullable=True)
    op.alter_column('recall_cards', 'topic',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('recall_cards', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('learning_sessions', 'interaction_pattern',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('learning_sessions', 'retention_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('learning_sessions', 'time_spent',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('learning_sessions', 'content_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('learning_sessions', 'topic',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('learning_sessions', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('knowledge_decay_events', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('knowledge_decay_events', 'decay_model_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('knowledge_decay_events', 'review_suggested',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('knowledge_decay_events', 'predicted_forget_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('knowledge_decay_events', 'last_interaction',
               existing_type=sa.TIMESTAMP(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('knowledge_decay_events', 'topic',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###
